---
- name: Include OS-Specific variables
  ansible.builtin.include_vars: "{{ ansible_os_family | lower }}.yml"

- name: Define jenkins_repo_url
  ansible.builtin.set_fact:
    jenkins_repo_url: "{{ __jenkins_repo_url }}"
  when: jenkins_repo_url is not defined

- name: Define jenkins_repo_key_url
  ansible.builtin.set_fact:
    jenkins_repo_key_url: "{{ __jenkins_repo_key_url }}"
  when: jenkins_repo_key_url is not defined

- name: Define jenkins_pkg_url
  ansible.builtin.set_fact:
    jenkins_pkg_url: "{{ __jenkins_pkg_url }}"
  when: jenkins_pkg_url is not defined

- name: Install Jenkins
  ansible.builtin.include_tasks: "setup-{{ ansible_os_family | lower }}.yml"

- name: Update Jenkins systemd unit file
  ansible.builtin.template:
    src: override.conf.j2
    dest: /etc/systemd/system/jenkins.service.d/override.conf
    mode: "0644"
  when: jenkins_systemd_unit_envs is defined and jenkins_systemd_unit_envs
  notify: Reload systemd units

- name: Set up Nginx
  ansible.builtin.include_tasks:
    file: "setup-nginx.yml"
  when: jenkins_nginx_proxy

- name: Set up Plugin
  ansible.builtin.include_tasks:
    file: "setup-plugin.yml"
