---
- name: Include OS-Specific variables
  ansible.builtin.include_vars: "{{ ansible_os_family | lower }}.yml"

- name: Define jenkins_repo_url
  ansible.builtin.set_fact:
    jenkins_repo_url: "{{ __jenkins_repo_url }}"
  when: jenkins_repo_url is not defined

- name: Define jenkins_repo_key_url
  ansible.builtin.set_fact:
    jenkins_repo_key_url: "{{ __jenkins_repo_key_url }}"
  when: jenkins_repo_key_url is not defined

- name: Define jenkins_pkg_url
  ansible.builtin.set_fact:
    jenkins_pkg_url: "{{ __jenkins_pkg_url }}"
  when: jenkins_pkg_url is not defined

- name: Install Jenkins
  ansible.builtin.include_tasks: "setup-{{ ansible_os_family | lower }}.yml"

- name: Ensure Jenkins systemd unit file dir exists
  ansible.builtin.file:
    path: /etc/systemd/system/jenkins.service.d
    state: directory
    mode: "0755"

- name: Update Jenkins systemd unit file
  ansible.builtin.template:
    src: override.conf.j2
    dest: /etc/systemd/system/jenkins.service.d/override.conf
    mode: "0644"
  notify: Reload systemd units

- name: Set up Nginx
  ansible.builtin.include_tasks:
    file: "setup-nginx.yml"
  when: jenkins_nginx_proxy

- name: Set up Plugin
  ansible.builtin.include_tasks:
    file: "setup-plugin.yml"
  when: jenkins_plugin_file

- name: Set up JCasc
  ansible.builtin.include_tasks:
    file: "setup-jcasc.yml"
  when: jenkins_jcasc_template

- name: Set up Seed job
  ansible.builtin.include_tasks:
    file: "setup-seedjob.yml"
  when: jenkins_seed_job_file
