---
# https://www.jenkins.io/doc/book/installing/linux/#debianubuntu

# See: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=863199 and
# https://github.com/geerlingguy/ansible-role-java/issues/64
- name: Ensure man directory exists.
  ansible.builtin.file:
    path: /usr/share/man/man1
    state: directory
    mode: "0755"

- name: Ensure dependencies are installed.
  ansible.builtin.apt:
    name:
      - curl
      - apt-transport-https
      - gnupg
      - net-tools
      - openjdk-11-jdk
    state: present
    update_cache: true

- name: Add Jenkins apt repository
  block:
    - name: Add Jenkins apt repository key.
      ansible.builtin.get_url:
        url: "{{ jenkins_repo_key_url }}"
        dest: "{{ jenkins_keyring }}"
        mode: "0644"

    - name: Add Jenkins apt repository file.
      ansible.builtin.apt_repository:
        repo: "{{ jenkins_repo_url }}"
        state: present
        filename: jenkins
      when: jenkins_repo_url | default(false)

- name: Install Jenkins
  block:
    # Inhibits service start
    # https://askubuntu.com/a/501622
    - name: Avoid starting service
      ansible.builtin.copy:
        content: 'exit 101'
        dest: /usr/sbin/policy-rc.d
        mode: '0755'

    - name: Install Jenkins
      ansible.builtin.package:
        name: "jenkins={{ jenkins_version }}"
        state: present

    - name: Remove policy-rc.d
      ansible.builtin.file:
        path: /usr/sbin/policy-rc.d
        state: absent
