---
# https://www.jenkins.io/doc/book/installing/linux/#red-hat-centos
- name: Ensure dependencies are installed.
  ansible.builtin.package:
    name:
      - curl
    state: present

- name: Add Jenkins repo GPG key.
  ansible.builtin.rpm_key:
    state: present
    key: "{{ jenkins_repo_key_url }}"
  when: jenkins_repo_url | default(false)

- name: Ensure Jenkins repo is installed.
  ansible.builtin.get_url:
    url: "{{ jenkins_repo_url }}"
    dest: /etc/yum.repos.d/jenkins.repo
    mode: "0644"
  environment: "{{ jenkins_download_proxy if (jenkins_proxy_host and jenkins_proxy_port) else {} }}"
  when: jenkins_repo_url | default(false)

- name: Download specific Jenkins version.
  ansible.builtin.get_url:
    url: "{{ jenkins_pkg_url }}/jenkins-{{ jenkins_version }}-1.1.noarch.rpm"
    dest: "/tmp/jenkins-{{ jenkins_version }}-1.1.noarch.rpm"
    mode: "0644"
  environment: "{{ jenkins_download_proxy if (jenkins_proxy_host and jenkins_proxy_port) else {} }}"

- name: Install our specific version of Jenkins.
  ansible.builtin.package:
    name: "/tmp/jenkins-{{ jenkins_version }}-1.1.noarch.rpm"
    state: present
