---
- name: Restart Jenkins
  ansible.builtin.service:
    name: jenkins
    state: restarted

- name: Reload systemd units
  ansible.builtin.systemd:
    daemon_reload: true

- name: Restart Nginx
  ansible.builtin.service:
    name: nginx
    state: restarted
