---
- name: Converge
  hosts: all
  vars:
    jdk_version: 21.0.2
    jenkins_java_home: /opt/jdk-21.0.2
    jenkins_plugin_file: plugins.txt
    jenkins_jcasc_template: jenkins.yaml.j2
    jenkins_systemd_unit_envs:
      java_home: "{{ jenkins_java_home }}"
  tasks:
    - name: "Include zhan9san.java"
      ansible.builtin.include_role:
        name: "zhan9san.java"
    - name: "Include zhan9san.jenkins"
      ansible.builtin.include_role:
        name: "zhan9san.jenkins"
